version: "3.8"
services:
  db:
    container_name: db_container
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: social_network
    volumes:
      - data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    container_name: server_container
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  data:
