{
 "title": "PostgreSQL Database",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "2023-05-07T09:54:00.000Z", "to": "2023-05-07T09:58:00.000Z" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
   },
   {
    "name": "release",
    "label": "Release",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(pg_up{release=\"$release\"})"
   },
   { "name": "datname", "label": "Database", "query": "label_values(datname)" },
   {
    "name": "mode",
    "label": "Lock table",
    "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
   },
   {
    "name": "host",
    "label": "host",
    "query": "db_container:5432, db_async_container:5432"
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{release=\"$release\", instance=\"$instance\", server=~\"$host\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_postmaster_start_time_seconds{release=\"$release\", instance=\"$instance\", server=~\"$host\"} * 1000"
    }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\", server=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{release=\"$release\", datname=~\"$datname\", instance=~\"$instance\", server=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\", server=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{release=\"$release\", instance=\"$instance\", server=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{release=\"$release\", instance=\"$instance\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average CPU %",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{release=\"$release\", instance=\"$instance\"}[5m]) * 10",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{release=\"$release\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{release=\"$release\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{release=\"$release\", instance=\"$instance\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{instance=\"$instance\", server=~\"$host\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{instance=\"$instance\", server=~\"$host\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{instance=\"$instance\", server=~\"$host\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{instance=\"$instance\", server=~\"$host\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{instance=\"$instance\", server=~\"$host\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_random_page_cost{instance=\"$instance\", server=~\"$host\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Seq Page Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_seq_page_cost{server=~\"$host\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{instance=\"$instance\", server=~\"$host\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{instance=\"$instance\", server=~\"$host\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state=\"active\", server=~\"$host\"} !=0",
     "legendFormat": "{{server}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{instance=\"$instance\", datname=~\"$datname\", server=~\"$host\"}[5m])",
     "legendFormat": "{{server}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{server}} rollbacks"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\", server=~\"$host\"}[1m]) != 0",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(pg_stat_database_tup_returned{datname=~\"$datname\", instance=~\"$instance\", server=~\"$host\"}[1m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$instance\", server=~\"$host\"} != 0",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\", server=~\"$host\"} != 0",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Idle sessions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state=~\"idle|idle in transaction|idle in transaction (aborted)\", server=~\"$host\"}",
     "legendFormat": "{{server}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{instance=\"$instance\", datname=~\"$datname\", server=~\"$host\"} / (pg_stat_database_blks_read{instance=\"$instance\", datname=~\"$datname\", server=~\"$host\"} + pg_stat_database_blks_hit{instance=\"$instance\", datname=~\"$datname\", server=~\"$host\"})",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Temp File (Bytes)",
   "type": "timeseries",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{instance=\"$instance\", datname=~\"$datname\", server=~\"$host\"}[5m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_locks_count{datname=~\"$datname\", instance=~\"$instance\", mode=~\"$mode\", server=~\"$host\"} != 0",
     "legendFormat": "{{server}},{{mode}}"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{instance=\"$instance\", datname=~\"$datname\", server=~\"$host\"}[5m])",
     "legendFormat": "{{server}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{server}} deadlocks"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{datname=~\"$datname\", instance=~\"$instance\", server=~\"$host\"} != 0",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend{instance=\"$instance\", server=~\"$host\"}[5m])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc{instance=\"$instance\", server=~\"$host\"}[5m])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{instance=\"$instance\", server=~\"$host\"}[5m])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{instance=\"$instance\", server=~\"$host\"}[5m])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean{instance=\"$instance\", server=~\"$host\"}[5m])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{instance=\"$instance\", server=~\"$host\"}[5m])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{instance=\"$instance\"}[5m])",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  }
 ]
}