// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: dialog/dialog.proto

package dialog

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DialogAPI_Send_FullMethodName = "/post.DialogAPI/Send"
	DialogAPI_List_FullMethodName = "/post.DialogAPI/List"
)

// DialogAPIClient is the client API for DialogAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DialogAPIClient interface {
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type dialogAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewDialogAPIClient(cc grpc.ClientConnInterface) DialogAPIClient {
	return &dialogAPIClient{cc}
}

func (c *dialogAPIClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, DialogAPI_Send_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogAPIClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, DialogAPI_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DialogAPIServer is the server API for DialogAPI service.
// All implementations must embed UnimplementedDialogAPIServer
// for forward compatibility
type DialogAPIServer interface {
	Send(context.Context, *SendRequest) (*SendResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	mustEmbedUnimplementedDialogAPIServer()
}

// UnimplementedDialogAPIServer must be embedded to have forward compatible implementations.
type UnimplementedDialogAPIServer struct {
}

func (UnimplementedDialogAPIServer) Send(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedDialogAPIServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDialogAPIServer) mustEmbedUnimplementedDialogAPIServer() {}

// UnsafeDialogAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DialogAPIServer will
// result in compilation errors.
type UnsafeDialogAPIServer interface {
	mustEmbedUnimplementedDialogAPIServer()
}

func RegisterDialogAPIServer(s grpc.ServiceRegistrar, srv DialogAPIServer) {
	s.RegisterService(&DialogAPI_ServiceDesc, srv)
}

func _DialogAPI_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogAPIServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DialogAPI_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogAPIServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DialogAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DialogAPI_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogAPIServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DialogAPI_ServiceDesc is the grpc.ServiceDesc for DialogAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DialogAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "post.DialogAPI",
	HandlerType: (*DialogAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _DialogAPI_Send_Handler,
		},
		{
			MethodName: "List",
			Handler:    _DialogAPI_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dialog/dialog.proto",
}
